In [1]:
import numpy as np
import pandas as pd

## Question one

> If you’re given two lists:

A = [1,2,3,4,5,6], B = [13, 21, 34]

The task is to create a list with the elements of A and B in a single dimension with output:

A_B = [1,2,3,4,5,6,13, 21, 34]

Which of the following option is the best way to create this list?





In [2]:
A = [1,2,3,4,5,6]
B = [13, 21, 34]

In [5]:
A.extend(B)

In [6]:
print(A)

[1, 2, 3, 4, 5, 6, 13, 21, 34, 13, 21, 34]


## Question two 

> How do you create an identity matrix in python?


In [8]:
id_arr = np.identity(3)

In [9]:
print(id_arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [12]:
data_url = 'https://raw.githubusercontent.com/WalePhenomenon/climate_change/master/fuel_ferc1.csv'
fuel_df = pd.read_csv(data_url)

In [13]:
fuel_df.head(10)

record_id  utility_id_ferc1  report_year  \
0   f1_fuel_1994_12_1_0_7                 1         1994   
1  f1_fuel_1994_12_1_0_10                 1         1994   
2   f1_fuel_1994_12_2_0_1                 2         1994   
3   f1_fuel_1994_12_2_0_7                 2         1994   
4  f1_fuel_1994_12_2_0_10                 2         1994   
5  f1_fuel_1994_12_2_0_13                 2         1994   
6   f1_fuel_1994_12_2_1_1                 2         1994   
7  f1_fuel_1994_12_2_1_10                 2         1994   
8  f1_fuel_1994_12_2_2_10                 2         1994   
9   f1_fuel_1994_12_4_0_1                 4         1994   

       plant_name_ferc1 fuel_type_code_pudl fuel_unit  fuel_qty_burned  \
0              rockport                coal       ton        5377489.0   
1  rockport total plant                coal       ton       10486945.0   
2                gorgas                coal       ton        2978683.0   
3                 barry                coal       ton        3739484.0   
4             chickasaw                 gas       mcf          40533.0   
5   e. c. gaston-unit 5                coal       ton        2124933.0   
6      joseph m. farley             nuclear       kgU           2260.0   
7   resondent's portion                coal       ton        5372133.0   
8  respondent's portion                coal       ton         817520.0   
9             units 1-3                coal       ton        1471233.0   

   fuel_mmbtu_per_unit  fuel_cost_per_unit_burned  \
0            16.590000                      18.59   
1            16.592000                      18.58   
2            24.130000                      39.72   
3            23.950000                      47.21   
4             1.000000                       2.77   
5            23.922000                      44.24   
6             0.064094                      28.77   
7            24.840000                      58.54   
8            24.290000                      33.97   
9            22.484000                      28.73   

   fuel_cost_per_unit_delivered  fuel_cost_per_mmbtu  
0                         18.53                1.121  
1                         18.53                1.120  
2                         38.12                1.650  
3                         45.99                1.970  
4                          2.77                2.570  
5                         43.25                1.850  
6                          0.00                0.450  
7                         55.13                2.360  
8                         34.65                1.400  
9                         28.11                1.278

In [14]:
fuel_df.shape

(29523, 11)

In [15]:
fuel_df.describe()

utility_id_ferc1   report_year  fuel_qty_burned  fuel_mmbtu_per_unit  \
count      29523.000000  29523.000000     2.952300e+04         29523.000000   
mean         118.601836   2005.806050     2.622119e+06             8.492111   
std           74.178353      7.025483     9.118004e+06            10.600220   
min            1.000000   1994.000000     1.000000e+00             0.000001   
25%           55.000000   2000.000000     1.381700e+04             1.024000   
50%          122.000000   2006.000000     2.533220e+05             5.762694   
75%          176.000000   2012.000000     1.424034e+06            17.006000   
max          514.000000   2018.000000     5.558942e+08           341.260000   

       fuel_cost_per_unit_burned  fuel_cost_per_unit_delivered  \
count               29523.000000                  2.952300e+04   
mean                  208.649031                  9.175704e+02   
std                  2854.490090                  6.877593e+04   
min                  -276.080000                 -8.749370e+02   
25%                     5.207000                  3.778500e+00   
50%                    26.000000                  1.737100e+01   
75%                    47.113000                  4.213700e+01   
max                139358.000000                  7.964521e+06   

       fuel_cost_per_mmbtu  
count         29523.000000  
mean             19.304354  
std            2091.540939  
min             -41.501000  
25%               1.940000  
50%               4.127000  
75%               7.745000  
max          359278.000000

## Question three

> Which of the following fuel type code has the lowest average fuel cost per unit burned?

In [16]:
fuel_df.groupby('fuel_type_code_pudl')['fuel_cost_per_unit_burned'].mean()

fuel_type_code_pudl
coal         67.421830
gas          13.659397
nuclear    4955.157002
oil         168.877086
other        18.253856
waste        19.518122
Name: fuel_cost_per_unit_burned, dtype: float64

## Question four

> What is the standard deviation and 75th percentile of the measure of energy per unit (Fuel_mmbtu_per_unit) in two decimal places?

In [45]:
std = fuel_df['fuel_mmbtu_per_unit'].describe()['std']
seventy_fifth_percentile = fuel_df['fuel_mmbtu_per_unit'].describe()['75%']
round(std, 2), round(seventy_fifth_percentile, 2)

(10.6, 17.01)

## Question five

> What is the skewness and kurtosis for the fuel quantity burned in two decimal places?

In [22]:
skew = fuel_df['fuel_qty_burned'].skew()
kurtois = fuel_df['fuel_qty_burned'].kurt()
round(skew, 2), round(kurtois, 2)

(15.85, 651.37)

## Question six 

> Which feature has missing values and what is the total number of missing value and percentage of the missing rows as a factor of the total number of rows in three decimal places?

(Enter answer in the format: Feature: xxx, Total: xxx, Percent: xxx)

In [33]:
print(fuel_df.isnull().sum())

record_id                         0
utility_id_ferc1                  0
report_year                       0
plant_name_ferc1                  0
fuel_type_code_pudl               0
fuel_unit                       180
fuel_qty_burned                   0
fuel_mmbtu_per_unit               0
fuel_cost_per_unit_burned         0
fuel_cost_per_unit_delivered      0
fuel_cost_per_mmbtu               0
dtype: int64


In [39]:
missing_values = fuel_df.isnull().sum()
print('Total: {}'.format(missing_values['fuel_unit']))

Total: 180


In [34]:
percentage = fuel_df.isnull().sum().max() / len(fuel_df) * 100
print('Percent: {:.3f}'.format(percentage))

Percent: 0.610


## Question seven 

> The feature with missing values falls under what category? What missing value imputation technique would you use?

In [40]:
#

## Question eight 

> Which of the features has the second and third lowest correlation with the Fuel Cost Per Unit Burned?

In [41]:
fuel_df.corr()

utility_id_ferc1  report_year  fuel_qty_burned  \
utility_id_ferc1                      1.000000     0.093323        -0.057447   
report_year                           0.093323     1.000000         0.012952   
fuel_qty_burned                      -0.057447     0.012952         1.000000   
fuel_mmbtu_per_unit                  -0.066946    -0.110853        -0.080946   
fuel_cost_per_unit_burned            -0.037863     0.013599        -0.018535   
fuel_cost_per_unit_delivered         -0.016414    -0.014043        -0.003551   
fuel_cost_per_mmbtu                   0.006122     0.010261        -0.001896   

                              fuel_mmbtu_per_unit  fuel_cost_per_unit_burned  \
utility_id_ferc1                        -0.066946                  -0.037863   
report_year                             -0.110853                   0.013599   
fuel_qty_burned                         -0.080946                  -0.018535   
fuel_mmbtu_per_unit                      1.000000                  -0.010034   
fuel_cost_per_unit_burned               -0.010034                   1.000000   
fuel_cost_per_unit_delivered            -0.009039                   0.011007   
fuel_cost_per_mmbtu                     -0.005884                  -0.000437   

                              fuel_cost_per_unit_delivered  \
utility_id_ferc1                                 -0.016414   
report_year                                      -0.014043   
fuel_qty_burned                                  -0.003551   
fuel_mmbtu_per_unit                              -0.009039   
fuel_cost_per_unit_burned                         0.011007   
fuel_cost_per_unit_delivered                      1.000000   
fuel_cost_per_mmbtu                              -0.000109   

                              fuel_cost_per_mmbtu  
utility_id_ferc1                         0.006122  
report_year                              0.010261  
fuel_qty_burned                         -0.001896  
fuel_mmbtu_per_unit                     -0.005884  
fuel_cost_per_unit_burned               -0.000437  
fuel_cost_per_unit_delivered            -0.000109  
fuel_cost_per_mmbtu                      1.000000

## Question nine 

> For the fuel type coal, what is the percentage change in the fuel cost per unit burned in 1998 compared to 1994?

In [50]:
data_coal = fuel_df.loc[fuel_df['fuel_type_code_pudl'] == 'coal']
sum_cost_coal_by_year = data_coal.groupby('report_year')['fuel_cost_per_unit_burned'].sum()
year_1994 = sum_cost_coal_by_year[1994]
year_1998 = sum_cost_coal_by_year[1998]
percentage = ((year_1994 - year_1998)/year_1994)*100
print('percentage: {:.0f}%'.format(percentage))

percentage: 21%


## Question ten

> Which year has the highest average fuel cost per unit delivered?

In [44]:
fuel_df.groupby('report_year')['fuel_cost_per_unit_delivered'].mean()

report_year
1994       63.636060
1995       32.735269
1996     9196.705948
1997    11140.197239
1998      287.154420
1999       25.551627
2000      985.362877
2001       60.050396
2002       47.594361
2003       55.663493
2004      139.524275
2005       41.438184
2006       38.657484
2007       43.325023
2008       58.588197
2009      652.694163
2010       91.862105
2011       59.774667
2012       60.994502
2013      172.307591
2014      192.737183
2015      326.535511
2016      103.901761
2017       46.196861
2018      499.269966
Name: fuel_cost_per_unit_delivered, dtype: float64